---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dlresende/spring-petclinic.git
      branch: master

containers:
  maven: &maven
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.5.4-jdk-8-alpine


jobs:
  - name: build
    plan:
      - get: source-code

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code
              path: .

          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn package
