---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/spring-projects/spring-petclinic.git
      branch: master

containers:
  openjdk-8: &openjdk-8
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: openjdk
        tag: 8-jdk-slim

  cf-cli: &cf-cli
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *openjdk-8

          inputs:
            - name: source-code
              path: .

          run:
            path: /bin/sh
            args:
              - -c
              - |
                  ./mvnw package

  - name: deploy
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *openjdk-8

          inputs:
            - name: source-code

          run:
            path: /bin/sh
            args:
              - -c
              - |
                  cd source-code || exit 1
                  ./mvnw -q package
                  cp target/*.jar ../release-jar/

          outputs:
            - name: release-jar

      - task: deploy-to-staging
        config:
          <<: *cf-cli
          inputs:
            - name: release-jar
              path: .

          params:
            CF_API: ((cf_api))
            CF_USERNAME: ((cf_user))
            CF_PASSWORD: ((cf_password))
            CF_SPACE: ((cf_staging_space))
            CF_ORG: ((cf_org))
            APP_NAME: petclinic-((cf_staging_space))
            CF_DIAL_TIMEOUT: 60

          run:
            path: /bin/sh
            args:
              - -c
              - |
                cf api "$CF_API"
                cf auth "$CF_USERNAME" "$CF_PASSWORD"
                cf target -o "$CF_ORG" -s "$CF_SPACE"
                cf push "$APP_NAME" -p *.jar
