---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dlresende/spring-petclinic.git
      branch: master

containers:
  maven: &maven
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.5.4-jdk-8-alpine

  cf-cli: &cf-cli
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code

          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code
                mvn package

  - name: deploy
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code

          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code/
                mvn  package
                cp target/*.jar ../compiled-jar/

          outputs:
            - name: compiled-jar

      - task: deploy-to-staging
        config:
          <<: *cf-cli

          inputs:
            - name: source-code
            - name: compiled-jar

          params:
            CF_API: ((cf.api))
            CF_USERNAME: ((cf.username))
            CF_PASSWORD: ((cf.password))
            CF_SPACE: ((cf.staging_space))
            CF_ORG: ((cf.org))

          run:
            path: /bin/bash
            args:
              - -c
              - |
                cf api --skip-ssl-validation "$CF_API"
                cf auth
                cf target -o "$CF_ORG" -s "$CF_SPACE"
                cf push "petclinic-$CF_SPACE" -p compiled-jar/*.jar

      - task: run-smoke-tests
        config:
          <<: *cf-cli

          run:
            path: curl
            args:
              - --fail
              - http://petclinic-((cf.staging_space)).((cf.app_domain))
