---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dlresende/spring-petclinic.git
      branch: master

  - name: compiled-jar
    type: s3
    source:
      regexp: packages/spring-petclinic-(.*).jar
      bucket: ((s3_bucket))
      endpoint: ((s3_endpoint))
      disable_ssl: ((s3_disable_ssl))
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))

containers:
  maven: &maven
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.5.4-jdk-8-alpine

  cf-cli: &cf-cli
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code

          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code
                mvn package
                cp target/*.jar ../release-jar/

          outputs:
            - name: release-jar

      - put: compiled-jar
        params:
          file: release-jar/*.jar

  - name: deploy
    plan:
      - get: source-code
        passed:
          - build

      - get: compiled-jar
        trigger: true
        passed:
          - build

      - task: deploy-to-staging
        config:
          <<: *cf-cli

          inputs:
            - name: compiled-jar

          params:
            CF_API: ((cf_api))
            CF_USERNAME: ((cf_username))
            CF_PASSWORD: ((cf_password))
            CF_SPACE: ((cf_staging_space))
            CF_ORG: ((cf_org))

          run:
            path: /bin/bash
            args:
              - -c
              - |
                cf api --skip-ssl-validation "$CF_API"
                cf auth
                cf target -o "$CF_ORG" -s "$CF_SPACE"
                cf push "petclinic-$CF_SPACE" -p compiled-jar/*.jar

      - task: run-smoke-tests
        config:
          <<: *cf-cli

          run:
            path: curl
            args:
              - --fail
              - http://petclinic-((cf_staging_space)).((cf_app_domain))
