---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dlresende/spring-petclinic.git
      branch: master

  - name: compiled-jar
    type: s3
    source:
      regexp: spring-petclinic-(.*).jar
      bucket: ((s3.bucket))
      access_key_id: ((s3.access_key_id))
      secret_access_key: ((s3.secret_access_key))
      region_name: ((s3.region))

containers:
  maven: &maven
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.5.4-jdk-8-alpine

  cf-cli: &cf-cli
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code

          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-code
                mvn package
                cp target/*.jar ../release-jar/

          outputs:
            - name: release-jar

      - put: compiled-jar
        params:
          file: release-jar/*.jar

  - name: deploy
    plan:
      - get: source-code
        passed:
          - build

      - get: compiled-jar
        trigger: true
        passed:
          - build

      - task: deploy-to-staging
        config:
          <<: *cf-cli

          inputs:
            - name: compiled-jar
            - name: source-code

          params:
            CF_API: ((cf.api))
            CF_USERNAME: ((cf.username))
            CF_PASSWORD: ((cf.password))
            CF_SPACE: ((cf.staging_space))
            CF_ORG: ((cf.org))

          run:
            path: ./source-code/src/main/scripts/push-to-cloud-foundry
            args:
              - compiled-jar/*.jar

      - task: run-smoke-tests
        config:
          <<: *cf-cli

          run:
            path: curl
            args:
              - --fail
              - http://petclinic-((cf.staging_space)).((cf.app_domain))

  - name: release
    plan:
      - get: source-code
        passed:
          - deploy

      - get: compiled-jar
        passed:
          - deploy
        trigger: true

      - task: deploy-to-production
        config:
          <<: *cf-cli

          inputs:
            - name: source-code
            - name: compiled-jar

          params:
            CF_API: ((cf.api))
            CF_USERNAME: ((cf.username))
            CF_PASSWORD: ((cf.password))
            CF_SPACE: ((cf.prod_space))
            CF_ORG: ((cf.org))

          run:
            path: ./source-code/src/main/scripts/push-to-cloud-foundry
            args:
              - compiled-jar/*.jar
