---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/dlresende/spring-petclinic.git
      branch: master

  - name: compiled-jar
    type: s3
    source:
      regexp: packages/spring-petclinic-(.*).jar
      bucket: ((s3_bucket))
      endpoint: ((s3_endpoint))
      disable_ssl: ((s3_disable_ssl))
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))

containers:
  maven: &maven
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.5.4-jdk-8-alpine

  cf-cli: &cf-cli
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli

  jmeter: &jmeter
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: justb4/jmeter

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true

      - task: package
        config:
          <<: *maven

          inputs:
            - name: source-code

          outputs:
            - name: release-jar

          run:
            path: /bin/sh
            args:
              - -c
              - |
                  cd source-code
                  mvn package
                  cp target/*.jar ../release-jar/

      - put: compiled-jar
        params:
          file: release-jar/*.jar

  - name: deploy
    plan:
      - get: source-code
        passed:
          - build

      - get: compiled-jar
        trigger: true
        passed:
          - build

      - task: deploy-to-staging
        config:
          <<: *cf-cli

          inputs:
            - name: source-code
            - name: compiled-jar

          params:
            CF_API: ((cf_api))
            CF_USERNAME: ((cf_username))
            CF_PASSWORD: ((cf_password))
            CF_SPACE: ((cf_staging_space))
            CF_ORG: ((cf_org))

          run:
            path: ./source-code/src/main/scripts/push-to-cloud-foundry
            args:
              - compiled-jar/*.jar

      - task: run-smoke-tests
        config:
          <<: *cf-cli

          run:
            path: curl
            args:
              - -f
              - http://petclinic-((cf_staging_space)).((cf_app_domain))

  - name: test
    plan:
      - get: source-code
        passed:
          - deploy

      - get: compiled-jar
        passed:
          - deploy
        trigger: true

      - task: run-performance-tests
        config:
          <<: *jmeter

          inputs:
            - name: source-code

          params:
            PETCLINIC_HOST: https://petclinic-((cf_staging_space)).((cf_app_domain))
            PETCLINIC_PORT: 80

          run:
            path: ./source-code/src/main/scripts/run-performance-tests

  - name: release
    plan:
      - get: source-code
        passed:
          - test

      - get: compiled-jar
        passed:
          - test
        trigger: true

      - task: deploy-to-production
        config:
          <<: *cf-cli

          inputs:
            - name: source-code
            - name: compiled-jar

          params:
            CF_API: ((cf_api))
            CF_USERNAME: ((cf_username))
            CF_PASSWORD: ((cf_password))
            CF_SPACE: ((cf_prod_space))
            CF_ORG: ((cf_org))

          run:
            path: ./source-code/src/main/scripts/push-to-cloud-foundry
            args:
              - compiled-jar/*.jar
