---
resources:
    - name: source-code
      type: git
      source:
          uri: https://github.com/spring-projects/spring-petclinic.git
          branch: master

    - name: compiled-jar
      type: s3
      source:
          regexp: ((team))/packages/spring-petclinic-(.*).jar
          bucket: ((s3_bucket))
          endpoint: ((s3_endpoint))
          disable_ssl: ((s3_disable_ssl))
          access_key_id: ((s3_access_key_id))
          secret_access_key: ((s3_secret_access_key))

    - name: version
      type: semver
      source:
          driver: s3
          key: ((team))/release-version
          bucket: ((s3_bucket))
          endpoint: ((s3_endpoint))
          disable_ssl: ((s3_disable_ssl))
          access_key_id: ((s3_access_key_id))
          secret_access_key: ((s3_secret_access_key))

jobs:
    - name: build
      serial: true
      plan:
          - get: source-code
          - get: version
            params:
                pre: alpha
          - task: compile
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source:
                        repository: openjdk
                        tag: 8-jdk-slim
                inputs:
                    - name: source-code
                    - name: version
                run:
                    path: /bin/sh
                    args:
                        - -c
                        - |
                            set -eu
                            cd source-code
                            ./mvnw -q versions:set -DnewVersion=$(cat ../version/version)
                            ./mvnw -q package

                            cd ..

                            cp source-code/target/*.jar release-jar/
                outputs:
                    - name: release-jar
          - put: version
            params:
                file: version/version
          - put: compiled-jar
            params:
                file: release-jar/*.jar
